# steps:
#  - name: 'node'
#     entrypoint: 'yarn'
#      args: ['install']
#   - name: node
#     entrypoint: yarn
#     args: ["start"]
#   - name: "gcr.io/cloud-builders/gcloud"
#     args: ["app", "deploy"]
# timeout: "1600s"

steps:
  - name: "node"
    entrypoint: "yarn"
    args: ["install"]
    - name: node
    entrypoint: yarn
    args: ["start"]
    - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
